/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as FieldReportsRouteImport } from './routes/field-reports'
import { Route as MapRouteImport } from './routes/map'
import { Route as NineFacesRouteImport } from './routes/nine-faces'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ChapterSlugRouteImport } from './routes/chapter.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldReportsRoute = FieldReportsRouteImport.update({
  id: '/field-reports',
  path: '/field-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NineFacesRoute = NineFacesRouteImport.update({
  id: '/nine-faces',
  path: '/nine-faces',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterSlugRoute = ChapterSlugRouteImport.update({
  id: '/chapter/$slug',
  path: '/chapter/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/field-reports': typeof FieldReportsRoute
  '/map': typeof MapRoute
  '/nine-faces': typeof NineFacesRoute
  '/scout': typeof ScoutRoute
  '/unlock': typeof UnlockRoute
  '/chapter/$slug': typeof ChapterSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/field-reports': typeof FieldReportsRoute
  '/map': typeof MapRoute
  '/nine-faces': typeof NineFacesRoute
  '/scout': typeof ScoutRoute
  '/unlock': typeof UnlockRoute
  '/chapter/$slug': typeof ChapterSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dossier': typeof DossierRoute
  '/field-reports': typeof FieldReportsRoute
  '/map': typeof MapRoute
  '/nine-faces': typeof NineFacesRoute
  '/scout': typeof ScoutRoute
  '/unlock': typeof UnlockRoute
  '/chapter/$slug': typeof ChapterSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dossier'
    | '/field-reports'
    | '/map'
    | '/nine-faces'
    | '/scout'
    | '/unlock'
    | '/chapter/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dossier'
    | '/field-reports'
    | '/map'
    | '/nine-faces'
    | '/scout'
    | '/unlock'
    | '/chapter/$slug'
  id:
    | '__root__'
    | '/'
    | '/dossier'
    | '/field-reports'
    | '/map'
    | '/nine-faces'
    | '/scout'
    | '/unlock'
    | '/chapter/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DossierRoute: typeof DossierRoute
  FieldReportsRoute: typeof FieldReportsRoute
  MapRoute: typeof MapRoute
  NineFacesRoute: typeof NineFacesRoute
  ScoutRoute: typeof ScoutRoute
  UnlockRoute: typeof UnlockRoute
  ChapterSlugRoute: typeof ChapterSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-reports': {
      id: '/field-reports'
      path: '/field-reports'
      fullPath: '/field-reports'
      preLoaderRoute: typeof FieldReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nine-faces': {
      id: '/nine-faces'
      path: '/nine-faces'
      fullPath: '/nine-faces'
      preLoaderRoute: typeof NineFacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$slug': {
      id: '/chapter/$slug'
      path: '/chapter/$slug'
      fullPath: '/chapter/$slug'
      preLoaderRoute: typeof ChapterSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DossierRoute: DossierRoute,
  FieldReportsRoute: FieldReportsRoute,
  MapRoute: MapRoute,
  NineFacesRoute: NineFacesRoute,
  ScoutRoute: ScoutRoute,
  UnlockRoute: UnlockRoute,
  ChapterSlugRoute: ChapterSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
